port: :8080
uploadDir: ./files
maxStorage: 10GB
previewMaxSize: 10MB
logDir: ./logs
logLevel: info
logMaxSize: 100MB
logMaxBackups: 7
logMaxAge: 30
users:
    - username: root
      password: $2a$10$vXnTer/QpbtsIdvWBW6sa.5RGpJh7NNPkHgH3Ke7k3fdrxW.4RcXK
      type: root
      displayName: Root
    - username: admin
      password: $2a$10$9SiUsSGb7WMh6uChGCcu1eYsaqnZugBYyzKmeNu3mT/928Tj.A29m
      type: admin
      displayName: Admin
    - username: user
      password: $2a$10$UV0YDTSszdotyFjzS0eNG.qUUiW7UH0PNJ2Ffew/uT7m4Z14al4iC
      type: user
      displayName: User
