port: :8080
uploadDir: ./files
maxStorage: 10GB
previewMaxSize: 10MB
logDir: ./logs
logLevel: info
logMaxSize: 100MB
logMaxBackups: 7
logMaxAge: 30
users:
    - username: root
      password: $2a$10$Yn/xIAASxCy2zGReVrxnve8K7ojKh6U3P977IcaEAp5dcp44ODTca
      type: root
      displayName: Root
    - username: admin
      password: $2a$10$KiUQJi1a6vG8Uykv817f2.D2SEXhlF0iCT3bFyh1Cn5u9cFgwQ07.
      type: admin
      displayName: Admin
    - username: user
      password: $2a$10$ysnNfYDtOMeeVuXTE02akuFKRpR0ZsqwHdTkY/FEYjnyEU6wA39We
      type: user
      displayName: User
